# Generated by Django 4.2.4 on 2023-12-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfsigneddocument',
            name='file',
            field=models.FileField(upload_to='storage'),
        ),
    ]
